name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-ci-cd-example:latest .

      # Pousser l'image Docker
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-ci-cd-example:latest
